"use client";

import PlanetBackground from "@/components/visuals/PlanetBackground";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-brand text-white p-8">
      <PlanetBackground />
      <div className="max-w-3xl mx-auto space-y-6 p-10 bg-white/4 rounded-xl mt-6">
        <h1 className="text-3xl font-bold mb-4">📜 Terms of Service</h1>
        <p>
          By using this app, you agree to the following terms. This app is an
          experimental project created for educational/demo purposes.
        </p>

        <section>
          <h2 className="text-xl font-semibold mb-2">Purpose</h2>
          <p className="text-gray-300">
            This app provides guided meditations generated by AI. It is intended
            as a mindfulness tool, not a substitute for medical or therapeutic
            care.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Use at Your Own Risk</h2>
          <p className="text-gray-300">
            Meditation can be supportive, but results may vary. Use at your own
            discretion.
          </p>
        </section>
        <section>
          <h2 className="text-xl font-semibold mb-2">
            Limitations of Liability
          </h2>
          <p className="text-gray-300">
            This app is provided “as is,” without any warranties or guarantees.
            We are not liable for any damages, losses, injuries, or consequences
            arising from the use of the app, reliance on its content, or
            participation in guided meditations. Use of this app is entirely at
            your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Eligibility</h2>
          <p className="text-gray-300">
            You must be at least 16 years old to use this app. By using it, you
            confirm you meet this requirement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Data Use</h2>
          <p className="text-gray-300">
            By using the app, you agree that your anonymized moods and notes may
            be sent to AI services (like OpenAI) for meditation generation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Service Changes</h2>
          <p className="text-gray-300">
            This app may change or shut down at any time as it is an
            experimental project. We make no guarantees of uptime or continued
            availability.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Contact</h2>
          <p className="text-gray-300">
            For questions, contact us at{" "}
            <span className="text-purple-300">support@example.com</span>.
          </p>
        </section>
      </div>
    </div>
  );
}
